apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: virtual-garden-kube-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: virtual-garden
      component: kube-apiserver
