apiVersion: v1
kind: Secret
metadata:
  name: virtual-garden-kube-controller-manager
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.tls.kubeAPIServer.ca.crt | b64enc }}
  tls.crt: {{ .Values.tls.kubeControllerManager.crt | b64enc }}
  tls.key: {{ .Values.tls.kubeControllerManager.key | b64enc }}
  kubeconfig: {{ include "virtual-garden.kubeconfig-controller-manager" . | b64enc }}
