apiVersion: v1
kind: Secret
metadata:
  name: virtual-garden-kube-aggregator-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.kubeAggregator.ca.crt | b64enc }}
  ca.key: {{ .Values.tls.kubeAggregator.ca.key | b64enc }}
