apiVersion: v1
kind: Secret
metadata:
  name: virtual-garden-kube-aggregator
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.kubeAggregator.client.crt | b64enc }}
  tls.key: {{ .Values.tls.kubeAggregator.client.key | b64enc }}
