apiVersion: v1
kind: Secret
metadata:
  name: identity-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.identity.ca.crt | b64enc }}
  ca.key: {{ .Values.tls.identity.ca.key | b64enc }}
