apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-client
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.tls.ca.crt | b64enc }}
  tls.crt: {{ .Values.tls.client.crt | b64enc }}
  tls.key: {{ .Values.tls.client.key | b64enc }}
