{{- if .Values.backup.storageProvider }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-backup
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ toYaml .Values.backup.secretData | indent 2 }}
{{- end }}
