apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-ca
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.ca.crt | b64enc }}
  ca.key: {{ .Values.tls.ca.key | b64enc }}
