# Secret containing cloud provider credentials for GCP project into which the Seed cluster have been provisioned.
---
apiVersion: v1
kind: Secret
metadata:
  name: seed-gcp
  namespace: garden
type: Opaque
data:
{{- range $key, $value := .Values.seed.iaascreds }}
  {{ $key }}: {{ print $value | b64enc }}
{{- end }}
  kubeconfig: {{ .Values.seed.kubeconfig | b64enc }}