# Seed cluster registration manifest into which the control planes of Shoot clusters will be deployed.
---
apiVersion: garden.sapcloud.io/v1beta1
kind: Seed
metadata:
  name: gcp
spec:
  cloud:
    profile: gcp
    region: {{ .Values.region }}
  secretRef:
    name: seed-gcp
    namespace: garden
  ingressDomain: {{ .Values.seed.ingressDomain }}
  networks: # Seed and Shoot networks must be disjunct
    nodes: {{ .Values.seed.networks.nodeCIDR }}
    pods: {{ .Values.seed.networks.podCIDR }}
    services: {{ .Values.seed.networks.serviceCIDR }}