namespace: xxx
serviceName: virtual-garden-kube-apiserver
images:
  hyperkube: k8s.gcr.io/hyperkube:v1.12.3

replicas: 3
apiServer:
  hostname: 127.0.0.1
  serviceName: virtual-garden-kube-apiserver
#  oidcIssuerURL: https://identity.ingress.garden2.dev.k8s.ondemand.com

tls:
  kubeAPIServer:
    ca:
      crt: ca-certificate
      key: ca-key
    server:
      crt: server-certificate
      key: server-key
    basicAuthPassword: password
  kubeControllerManager:
    crt: client-certificate
    key: client-key
  admin:
    crt: client-certificate
    key: client-key
  serviceAccountKey: key